

# ================================ INFORMATIONS =============================================
informations:
  version: 1.0.0
# =================================== STEPS =================================================
program_steps:
  download_data: False
  insert_data: False
  plot_graph: True
# ================================== OPTIONS ================================================
options:
  word_per_page: 20
  waiting_time: 1
# =================================== GRAPH =================================================
plot_graph:
  width: 100
  height: 100
